#!/bin/bash
# First-boot provisioning for plain-hyprland (runs as root from
# hypr-qa-provision.service, installed by the cloud-init seed).
# Writes ok|fail to /var/lib/hypr-qa/status; the host's `build` polls it.
set -euo pipefail

STATE=/var/lib/hypr-qa
SHARE=/usr/local/share/hypr-qa
QA_USER=qa
mkdir -p "$STATE"
exec > >(tee -a /var/log/hypr-qa-provision.log) 2>&1
echo running >"$STATE/status"
trap 'rc=$?; [ $rc -eq 0 ] || { echo "provision failed (rc=$rc, line $LINENO)"; echo fail >"$STATE/status"; }' EXIT

echo "== $(date -u +%FT%TZ) provisioning"

# The image's keyring can be older than current package signatures; refresh
# it first, then do a full upgrade together with the install (Arch does not
# support partial upgrades).
pacman -Sy --noconfirm archlinux-keyring
pacman -Syu --noconfirm --needed \
    hyprland mesa \
    foot \
    ttf-dejavu \
    greetd

echo "== installed: $(pacman -Q hyprland foot greetd mesa | tr '\n' ' ')"

# Hyprland config: the stock example config of the installed version, with
# the terminal set to foot, plus the QA overrides. A real (non-autogenerated)
# config also keeps the first-launch welcome app from starting.
home=$(getent passwd "$QA_USER" | cut -d: -f6)
install -d -o "$QA_USER" -g "$QA_USER" "$home/.config" "$home/.config/hypr"
cfg="$home/.config/hypr/hyprland.lua"
sed -E 's/^(local terminal[[:space:]]*=[[:space:]]*)"kitty"/\1"foot"/' /usr/share/hypr/hyprland.lua >"$cfg"
grep -qE '^local terminal[[:space:]]*=[[:space:]]*"foot"' "$cfg" \
    || echo "WARN: stock config has no kitty terminal line; terminal not switched to foot"
cat "$SHARE/hyprland-qa.lua" >>"$cfg"
chown "$QA_USER:$QA_USER" "$cfg"

# foot: a font size OCR reads reliably.
install -d -o "$QA_USER" -g "$QA_USER" "$home/.config/foot"
install -m 0644 -o "$QA_USER" -g "$QA_USER" "$SHARE/foot.ini" "$home/.config/foot/foot.ini"

# greetd: keep the shipped default_session (agreety on tty1) and add an
# initial_session that autologs qa into Hyprland on every boot.
[ -f /etc/greetd/config.toml.orig ] || cp /etc/greetd/config.toml /etc/greetd/config.toml.orig
cat /etc/greetd/config.toml.orig "$SHARE/greetd-autologin.toml" >/etc/greetd/config.toml
systemctl enable greetd.service

# The cloud image orders sshd after time-sync.target via
# systemd-time-wait-sync, and timesyncd's first NTP sync through QEMU
# user networking took ~77 s here, so ssh came up ~70 s after the session.
# The guest clock comes from the host RTC (and `vm restore` resyncs it), so
# don't wait for NTP.
systemctl mask systemd-time-wait-sync.service

echo "== $(date -u +%FT%TZ) provisioning done"
touch "$STATE/provisioned"
echo ok >"$STATE/status"
